version: '3'
services:
  file_checker:
    image: ghcr.io/junjiequan/file-checker-service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app:/home/node/app/files #location of the zipped files
      - /nfs/groups/beamlines:/nfs/groups/beamlines
      - /ess/data:/ess/data
      - /users/detector/experiments/:/users/detector/experiments
      - /mnt/groupdata:/mnt/groupdata
      - /mnt/groupdata/guide_optimizations/:/mnt/groupdata/guide_optimizations
    environment:
      - USERNAME=<STR>
      - PASSWORD_STAGING=<STR>
      - PASSWORD_PROD=<STR>
      - SSC_BASE_URL=<STR>
      - PSC_BASE_URL=<STR>
      - NO_PROXY=<STR>
      - HTTP_PROXY=<STR>
      - HTTPS_PROXY=<STR>
    ports:
      - '8000:8000'
